print("Введите имя")
name = input()
print("Введите фамилию")
surname = input()
print("Введите год рождения")
age = input()
print(name+"_"+surname+"_"+age)
name, surname = surname, name
age = str(int(age) + 60)
print(name+"_"+surname+"_"+age)
